name: Environment Variables
on: workflow_dispatch
env:
  project-name: Ci CD react
jobs:
  env-variables-demo:
    env:
      job-name: First_job
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow level environment variable
        run: echo $project-name
      - name: Print Job Level environment variable
        run: echo $job-name
      - name: Print Step Level environment variable
        env:
          step-details: executing step level variable
        run: echo $step-details
