name: Github Context
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Context
        env:
          cacheName: cache-the-context
        run: |
          echo "$cacheName"
          echo "${{ toJSON(github)}}"
