name: Deployment
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test -- --watchAll=false
  deploye:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Deploy Code
        run: echo "Deploying Code"
