name: Main Branch Push
on:
  push:
    branches:
      - main
jobs:
  main-branch-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test Project
        run: npm run test
